# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# MaxEntRasterPrep.py
# Created on: 2016-08-26 14:20:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: MaxEntRasterPrep <Input_Raster_Layer> <OutputRaster_asc> <nlcd270_asc> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Input_Raster_Layer = arcpy.GetParameterAsText(0)

OutputRaster_asc = arcpy.GetParameterAsText(1)

nlcd270_asc = arcpy.GetParameterAsText(2)
if nlcd270_asc == '#' or not nlcd270_asc:
    nlcd270_asc = "C:\\Users\\Dorn\\SharePoint\\WHCR Migration Stopover Habit - Dat\\Maxent\\layers\\nlcd270.asc" # provide a default value if unspecified

# Local variables:
bio_1_Resample_tif = ""

# Process: Resample
tempEnvironment0 = arcpy.env.snapRaster
arcpy.env.snapRaster = nlcd270.asc
tempEnvironment1 = arcpy.env.extent
arcpy.env.extent = nlcd270.asc
arcpy.Resample_management(Input_Raster_Layer, bio_1_Resample_tif, nlcd270_asc, "NEAREST")
arcpy.env.snapRaster = tempEnvironment0
arcpy.env.extent = tempEnvironment1

# Process: Raster to ASCII
arcpy.RasterToASCII_conversion(bio_1_Resample_tif, OutputRaster_asc)

