# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# PointRaster.py
# Created on: 2014-03-28 12:04:31.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
from arcpy.sa import *

arcpy.env.scratchWorkspace = "c:\\Users\\dorn.SAVINGCRANES\\Desktop\\WhooperWanderings.gdb"
arcpy.env.workspace = "c:\\Users\\dorn.SAVINGCRANES\\Desktop\\WhooperWanderings.gdb"

# Local variables:
points= "DAR_ptts"
snapraster = "Wis10kRaster"
postquery = "DARyearQuery"
points_2 = "DAR_ptts"

rows = arcpy.SearchCursor(postquery)
total = arcpy.GetCount_management(postquery)
count = 0
for row in rows:
    expression = row.query
    output_raster = row.outputname
    t_raster = "t_"+output_raster

    count = count+1
    arcpy.AddWarning("\nCreating raster number " + str(count) + " of " + str(total) + ".")

    # Process: Select Layer By Attribute
    arcpy.SelectLayerByAttribute_management(points, "NEW_SELECTION", expression)

    # Process: Point to Raster
    tempEnvironment0 = arcpy.env.snapRaster
    arcpy.env.snapRaster = snapraster
    tempEnvironment1 = arcpy.env.extent
    arcpy.env.extent = snapraster
    arcpy.PointToRaster_conversion(points, "OBJECTID", t_raster, "COUNT", "NONE", snapraster)
    arcpy.env.snapRaster = tempEnvironment0
    arcpy.env.extent = tempEnvironment1
    out_raster = Con(IsNull(t_raster),0, t_raster)
    out_raster.save(output_raster)
